// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace AudioRecognition_ML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public float Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public float Col8 { get; set; }


        [ColumnName("col9"), LoadColumn(9)]
        public float Col9 { get; set; }


        [ColumnName("col10"), LoadColumn(10)]
        public float Col10 { get; set; }


        [ColumnName("col11"), LoadColumn(11)]
        public float Col11 { get; set; }


        [ColumnName("col12"), LoadColumn(12)]
        public float Col12 { get; set; }


        [ColumnName("col13"), LoadColumn(13)]
        public float Col13 { get; set; }


        [ColumnName("col14"), LoadColumn(14)]
        public float Col14 { get; set; }


        [ColumnName("col15"), LoadColumn(15)]
        public float Col15 { get; set; }


        [ColumnName("col16"), LoadColumn(16)]
        public float Col16 { get; set; }


        [ColumnName("col17"), LoadColumn(17)]
        public float Col17 { get; set; }


        [ColumnName("col18"), LoadColumn(18)]
        public float Col18 { get; set; }


        [ColumnName("col19"), LoadColumn(19)]
        public float Col19 { get; set; }


        [ColumnName("col20"), LoadColumn(20)]
        public float Col20 { get; set; }


        [ColumnName("col21"), LoadColumn(21)]
        public float Col21 { get; set; }


        [ColumnName("col22"), LoadColumn(22)]
        public float Col22 { get; set; }


        [ColumnName("col23"), LoadColumn(23)]
        public float Col23 { get; set; }


        [ColumnName("col24"), LoadColumn(24)]
        public float Col24 { get; set; }


        [ColumnName("col25"), LoadColumn(25)]
        public float Col25 { get; set; }


        [ColumnName("col26"), LoadColumn(26)]
        public float Col26 { get; set; }


        [ColumnName("col27"), LoadColumn(27)]
        public float Col27 { get; set; }


        [ColumnName("col28"), LoadColumn(28)]
        public float Col28 { get; set; }


        [ColumnName("col29"), LoadColumn(29)]
        public float Col29 { get; set; }


        [ColumnName("col30"), LoadColumn(30)]
        public float Col30 { get; set; }


        [ColumnName("col31"), LoadColumn(31)]
        public float Col31 { get; set; }


        [ColumnName("col32"), LoadColumn(32)]
        public float Col32 { get; set; }


        [ColumnName("col33"), LoadColumn(33)]
        public float Col33 { get; set; }


        [ColumnName("col34"), LoadColumn(34)]
        public float Col34 { get; set; }


        [ColumnName("col35"), LoadColumn(35)]
        public float Col35 { get; set; }


        [ColumnName("col36"), LoadColumn(36)]
        public float Col36 { get; set; }


        [ColumnName("col37"), LoadColumn(37)]
        public float Col37 { get; set; }


        [ColumnName("col38"), LoadColumn(38)]
        public float Col38 { get; set; }


        [ColumnName("col39"), LoadColumn(39)]
        public float Col39 { get; set; }


        [ColumnName("col40"), LoadColumn(40)]
        public float Col40 { get; set; }


        [ColumnName("col41"), LoadColumn(41)]
        public float Col41 { get; set; }


        [ColumnName("col42"), LoadColumn(42)]
        public float Col42 { get; set; }


        [ColumnName("col43"), LoadColumn(43)]
        public float Col43 { get; set; }


        [ColumnName("col44"), LoadColumn(44)]
        public float Col44 { get; set; }


        [ColumnName("col45"), LoadColumn(45)]
        public float Col45 { get; set; }


        [ColumnName("col46"), LoadColumn(46)]
        public float Col46 { get; set; }


        [ColumnName("col47"), LoadColumn(47)]
        public float Col47 { get; set; }


        [ColumnName("col48"), LoadColumn(48)]
        public float Col48 { get; set; }


        [ColumnName("col49"), LoadColumn(49)]
        public float Col49 { get; set; }


        [ColumnName("col50"), LoadColumn(50)]
        public float Col50 { get; set; }


        [ColumnName("col51"), LoadColumn(51)]
        public float Col51 { get; set; }


        [ColumnName("col52"), LoadColumn(52)]
        public float Col52 { get; set; }


        [ColumnName("col53"), LoadColumn(53)]
        public float Col53 { get; set; }


        [ColumnName("col54"), LoadColumn(54)]
        public float Col54 { get; set; }


        [ColumnName("col55"), LoadColumn(55)]
        public float Col55 { get; set; }


        [ColumnName("col56"), LoadColumn(56)]
        public float Col56 { get; set; }


        [ColumnName("col57"), LoadColumn(57)]
        public float Col57 { get; set; }


        [ColumnName("col58"), LoadColumn(58)]
        public float Col58 { get; set; }


        [ColumnName("col59"), LoadColumn(59)]
        public float Col59 { get; set; }


        [ColumnName("col60"), LoadColumn(60)]
        public float Col60 { get; set; }


        [ColumnName("col61"), LoadColumn(61)]
        public float Col61 { get; set; }


        [ColumnName("col62"), LoadColumn(62)]
        public float Col62 { get; set; }


        [ColumnName("col63"), LoadColumn(63)]
        public float Col63 { get; set; }


        [ColumnName("col64"), LoadColumn(64)]
        public float Col64 { get; set; }


        [ColumnName("col65"), LoadColumn(65)]
        public float Col65 { get; set; }


        [ColumnName("col66"), LoadColumn(66)]
        public float Col66 { get; set; }


        [ColumnName("col67"), LoadColumn(67)]
        public float Col67 { get; set; }


        [ColumnName("col68"), LoadColumn(68)]
        public float Col68 { get; set; }


        [ColumnName("col69"), LoadColumn(69)]
        public float Col69 { get; set; }


        [ColumnName("col70"), LoadColumn(70)]
        public float Col70 { get; set; }


        [ColumnName("col71"), LoadColumn(71)]
        public float Col71 { get; set; }


        [ColumnName("col72"), LoadColumn(72)]
        public float Col72 { get; set; }


        [ColumnName("col73"), LoadColumn(73)]
        public float Col73 { get; set; }


        [ColumnName("col74"), LoadColumn(74)]
        public float Col74 { get; set; }


        [ColumnName("col75"), LoadColumn(75)]
        public float Col75 { get; set; }


        [ColumnName("col76"), LoadColumn(76)]
        public float Col76 { get; set; }


        [ColumnName("col77"), LoadColumn(77)]
        public float Col77 { get; set; }


        [ColumnName("col78"), LoadColumn(78)]
        public string Col78 { get; set; }


    }
}
